name: chat_messenger
description: chatting_app
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0 <4.0.0" # Minimum required Flutter SDK v3.19.0 or greater

# Dependencies:
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`.
# To see which dependencies have newer
# versions available on pub.dev, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
    
  # CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6

  # Firebase dependencies
  firebase_core: 2.25.4
  cloud_firestore: 4.15.5
  firebase_auth: 4.17.5
  firebase_storage: 11.6.6
  firebase_messaging: 14.7.16
  firebase_database: 10.4.6
  cloud_functions: 4.6.5
  google_mobile_ads: 4.0.0

  # App dependencies
  get: 4.6.6
  flutter_iconly: 1.0.2
  google_fonts: 6.1.0
  flutter_svg: 2.0.10+1
  cached_network_image: 3.3.1
  video_player: 2.8.2
  video_thumbnail: 0.5.3
  path_provider: 2.1.2
  path: 1.9.0
  timeago: 3.6.1
  share_plus: 7.2.2
  url_launcher: 6.2.5
  shared_preferences: 2.2.2
  camera: 0.10.5+9
  image_picker: 1.0.7
  image_cropper: 5.0.1
  permission_handler: 11.3.0
  country_code_picker: 3.0.0
  pin_code_fields: 8.0.1
  flutter_spinkit: 5.2.0
  http: 1.2.0
  googleapis_auth: 1.4.2
  easy_rich_text: 2.1.0
  shimmer: 3.0.0
  audioplayers: 5.2.1
  assets_audio_player: 3.1.1
  wechat_assets_picker: ^8.9.0-dev.1
  emoji_picker_flutter: 2.0.0
  giphy_get: 3.5.4
  file_picker: 6.1.1
  mime: 1.0.5
  chewie: 1.7.5
  uuid: 3.0.7
  marquee: 2.2.3
  geolocator: 11.0.0
  flutter_sound: 9.2.13
  encrypt: 5.0.3
  google_sign_in: 6.2.1
  sign_in_with_apple: 5.0.0
  crypto: 3.0.3
  agora_rtc_engine: 6.2.6
  flutter_ringtone_player: 4.0.0+2
  video_editor: 2.4.0
  fraction: 5.0.2
  story_view: 0.16.5
  async: 2.11.0
  rxdart: 0.27.7
  

dependency_overrides:
  modal_bottom_sheet: ^3.0.0-pre
  photo_manager: ^3.0.0-dev.2

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.0
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
    - assets/sounds/
    - assets/flags/
    - assets/icons/extensions/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

# Generate android & ios launcher icon settings
flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: "#ffffff"
  image_path: "assets/images/launcher_icon.png"

# Generate splash logo settings
flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#000000"
  image: "assets/images/app_logo.png"
  android: true
  ios: true 
  android_12:
    color: "#FFFFFF"
    color_dark: "#000000"
    image: "assets/images/app_logo.png"