// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqvHpUVffaa4GSHOene6PNBnpFQxDATto',
    appId: '1:848724543980:android:fbc532d2948abb74a598c9',
    messagingSenderId: '848724543980',
    projectId: 'flutter-chat-messenger-6bb5c',
    databaseURL: 'https://bau-pm-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'auth-4c590.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLDcPx6NZDKkBBAikseEl6gPF1EEhpdVs',
    appId: '1:99096378851:ios:6a96fb905fb4d334e874d6',
    messagingSenderId: '99096378851',
    projectId: 'bau-pm',
    databaseURL: 'https://bau-pm-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bau-pm.appspot.com',
    androidClientId: '99096378851-1rhb6j7dqo827ak978iv4ll7r1jqjpvv.apps.googleusercontent.com',
    iosClientId: '99096378851-1gr9hjbh6h050cjvkv2svdlobg1vosr7.apps.googleusercontent.com',
    iosBundleId: 'de.bau300.app1',
  );
}
